### ISSUE TITLE
unzip files if the resource is zipped

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/biodownload#13]

**Comment by belkassaby** [comment]
@pnrobinson do we want to be able to unzip only gz files? (where we expect only one file zipped) or zip archives as well? If zip archive as well, @ielis and I were discussing that maybe that shouldn't be the role of the library to unzip archives . What are your thoughts?

**Comment by belkassaby** [comment]
And actually gz files can also contain multiple compressed file...

**Comment by pnrobinson** [comment]
@belkassaby I would suggest let's move towards putting this onto maven central with the current functionality. We can return to the library and add features according to needs that come up or user requests. It is probably best not to make this library too fancy because our main need is just to download these files and I think lots of other ontology users will be the same

**Comment by belkassaby** [comment]
ok, that sounds good. I will leave the issue open for now.

**Comment by ielis** [comment]
I think we should not implement this function, as it may make the library unnecessarily complex and for me it seems to be out of scope.
