### ISSUE TITLE
DownloadableResource class

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/biodownload#2]
The Builder class could aggregate a list like this
```

private final List<DownloadableResource> resources;
public Builder() {
resources = new ArrayList<>();
}
(...)
public Builder hpoJson() {
  resources.add(new DownloadableResource.HPO_JSON);
  return this;
}
```
The Downloadable Resource class could look like this
```

private final String localName
private final String url;

public static DownloadableResource HP_JSON = new DownloadableResource("hp.json", "...the purl   ");
```

@ielis You were discussing have a File for the localName, but this would be error prone if the client code assigns the wrong local name by mistake. Maybe instead, the class should have the following method (note that we always know the download directory)

```
File getLocalFile(File downloadDirectory) {
  return new File (downloadDirectory + File.separator + new File(localName)):
}
```

@belkassaby

**Comment by ielis** [comment]
I am not 100% sure what the API should look like here, but generally, however, it's been more useful to use `File` or `Path` instead of `String` where the `String` represents file path. Most of the time, the `String fileName` has to be converted to `File fileName` anyway to do anything useful, e.g. test `fileName.isFile()`. Let's keep this in mind, when working on the `DownloadableResource` API.

**Comment by belkassaby** [comment]
You mean the localName/name in the example above? we replace it by a File/Path instead of having to create a File with the downloadDirectory/File.separator and filename when in the implementation. Ok, I'll work on a commit now.

**Comment by belkassaby** [comment]
@ielis Im encountering some issue with how to include a File/Path instead of the filename. Indeed, for the `File` I need to also have the `savingDirectory`, but how do we pass it for the resource instantiations  inside of the `DownloadableResource` class? 
That would work for the custom instantiation, but all the resource ones instantiated inside of the class. Maybe we can discuss that topic a bit more at 3pm.

**Comment by ielis** [comment]
Hi, sorry, this is probably my bad. I was talking about the `File`/`Path` at the wrong place. Let's discuss this during the call.
